{% set version = "1.4.1" %}

package:
  name: brewer2mpl
  version: {{ version }}

source:
  fn: brewer2mpl-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/brewer2mpl/brewer2mpl-{{ version }}.tar.gz
  sha256: 2e094d1bea766885aa77e4ed40cc718af6458a1d5e08cc87a5f453c6095b1b1c

build:

  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - brewer2mpl
    - brewer2mpl.wesanderson

about:
  home: https://github.com/jiffyclub/brewer2mpl/wiki
  license: MIT
  summary: Connect colorbrewer2.org color maps to Python and matplotlib

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
